version: "3.9"
services:
  mongodb:
    image: 'smish12/distributed_phase_1_database'
    volumes:
      - data:/data/db
    # env_file:
    #   - ./env/mongo.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    image: 'smish12/distributed_phase_1_backend'
    build: './backend'
    ports:
      - '80:80'  
    volumes:
      - logs:/app/logs 
      - ./backend:/app 
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    image: 'smish12/distributed_phase_1_frontend'
    
    build: './frontend'
    ports:
      - '3000:3000'  
    volumes:
      - logs:/app/logs 
      - ./frontend/src:/app /src
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  
volumes:
  data:
  logs:
    


